import csv
import json
import ast
import sys
mediu = {
    'i10': 'Essential (primary) hypertension',
    'oedeme': 'Edema',
    'douleurxx_irrad_@_mâchoire': 'Pain irradiating to jaw',
    'douleurxx_endroitducorps_@_orteil__2__D_': 'Pain at site: Toe (2nd) Right',
    'antipsy_récent': 'Recent antipsychotic medication use or withdrawal symptoms',
    'douleurxx_endroitducorps_@_nez': 'Pain at site: Nose',
    'sialorhee': 'Sialorrhea',
    'douleurxx_endroitducorps_@_creux_poplité_D_': 'Pain at site: Popliteal fossa Right',
    'douleurxx_endroitducorps_@_orteil__2__G_': 'Pain at site: Toe (2nd) Left',
    'douleurxx_endroitducorps_@_bas_du_thorax': 'Pain at site: Lower thorax',
    'douleurxx_precis_@_2': 'Precise pain: 2',
    'ptose': 'Ptosis',
    'douleurxx_endroitducorps_@_flanc_G_': 'Pain at site: Flank Left',
    'spasme_trapeze': 'Trapezius spasm',
    'lesions_peau_endroitducorps_@_petite_lèvre_G_': 'Skin lesions at site: Lower lip Left',
    'oedeme_endroitducorps_@_cuisse_D_': 'Edema at site: Thigh Right',
    'douleurxx_intens_@_1': 'Pain intensity: 1',
    'douleurxx_endroitducorps_@_bouche': 'Pain at site: Mouth',
    'smokingpast': 'Smoking past',
    'lesions_peau_endroitducorps_@_cartilage_thyroidien': 'Skin lesions at site: Thyroid cartilage',
    'boire_ped': 'Pediatric drinking',
    'douleurxx_endroitducorps_@_flanc_G_': 'Pain at site: Flank Left',
    'lesions_peau_endroitducorps_@_fesse_G_': 'Skin lesions at site: Buttock Left',
    'douleurxx_endroitducorps_@_haut_du_thorax': 'Pain at site: Upper thorax',
    'douleurxx_endroitducorps_@_creux_poplité_G_': 'Pain at site: Popliteal fossa Left',
    'douleurxx_endroitducorps_@_face_dorsale_du_pied_D_': 'Pain at site: Dorsal surface of foot Right',
    'prurit_occ': 'Itching',
    'oedeme_endroitducorps_@_joue_D_': 'Edema at site: Cheek Right',
    'douleurxx_endroitducorps_@_cheville_D_': 'Pain at site: Ankle Right',
    'douleurxx_endroitducorps_@_doigt_index__G_': 'Pain at site: Index finger Left',
    'g20': 'Parkinson\'s disease',
    'douleurxx_endroitducorps_@_colonne_cervicale': 'Pain at site: Cervical spine',
    'j44_j42': 'Chronic obstructive pulmonary disease (COPD)',
    'k21': 'Gastroesophageal reflux disease (GERD)',
    'J81': 'Pulmonary edema',
    'douleurxx_irrad_@_thorax_postérieur_G_': 'Pain irradiating to posterior thorax Left',
    'lesions_peau_endroitducorps_@_commissure_G_': 'Skin lesions at site: Corner of mouth Left',
    'immob1': 'Immobility',
    'lesions_peau_endroitducorps_@_avant-bras_G_': 'Skin lesions at site: Forearm Left',
    'douleurxx_soudain_@_0': 'Sudden pain: 0',
    'ap_fk': 'FK fusion protein',
    'j34.2': 'Nasal polyps',
    'patho_endo': 'Endocrine pathology',
    'i25.1': 'Atherosclerotic heart disease of native coronary artery',
    'lesions_peau_endroitducorps_@_épaule_D_': 'Skin lesions at site: Shoulder Right',
    'gorge_dlr': 'Throat pain',
    'j32': 'Chronic sinusitis',
    'vo_sg': 'Surgical voice alteration',
    'douleurxx_endroitducorps_@_sous_la_machoire': 'Pain at site: Submandibular area',
    'douleurxx_endroitducorps_@_orteil__1__D_': 'Pain at site: Toe (1st) Right',
    'douleurxx_carac_@_un_coup_de_couteau': 'Pain characteristic: Stabbing sensation',
    
    'malf_cardiaque': 'Cardiac disorder',
    'trav1_@_AmerS': 'Symptoms related to American Samoa',
    'lesions_peau_endroitducorps_@_cheville_D_': 'Skin lesions at site: Ankle Right',
    'rds_deg': 'Degree of respiratory distress',
    'm79.7': 'Fibromyalgia',
    'douleurxx_carac_@_sensible': 'Pain characteristic: Sensitive',
    'douleurxx_endroitducorps_@_pubis': 'Pain at site: Pubis',
    'douleurxx_endroitducorps_@_épaule_D_': 'Pain at site: Shoulder Right',
    'ménorr': 'Menorrhagia',
    'bw_bending': 'Backward bending',
    'rx_vasodil': 'Symptoms related to vasodilator medication use',
    'douleurxx_irrad_@_épaule_G_': 'Pain irradiating to shoulder Left',
    'douleurxx': 'Pain',
    'B34.9': 'Viral infection, unspecified',
    'vaccination': 'Vaccination',
    'pdc': 'Prescribed drug consumption',
    'lesions_peau_desquame_@_O': 'Skin lesions: Desquamation',
    'Mauv_aliment': 'Symptoms related to food poisoning',
    'douleurxx_precis_@_1': 'Precise pain: 1',
    'douleurxx_irrad_@_haut_du_thorax': 'Pain irradiating to upper thorax',
    'dayc': 'Symptoms occurring during the day',
    'gain_poids': 'Weight gain',
    'tagri': 'Irritation',
    'drink_energie': 'Energy drink consumption',
    'douleurxx_precis_@_5': 'Precise pain: 5',
    'e10_e11': 'Type 1 and Type 2 diabetes',
    'lesions_peau_endroitducorps_@_épaule_G_': 'Skin lesions at site: Shoulder Left',
    'lesions_peau_endroitducorps_@_biceps_D_': 'Skin lesions at site: Biceps Right',
    'z82.49': 'Family history of other disorder',
    'douleurxx_endroitducorps_@_face_dorsale_du_pied_G_': 'Pain at site: Dorsal surface of foot Left',
    'trav1_@_N': 'Symptoms related to Nauru',
    'perinatality': 'Symptoms related to the perinatal period',
    'lesions_peau_intens_@_6': 'Skin lesions intensity: 6',
    'faible': 'Weakness',
    'douleurxx_soudain_@_6': 'Sudden pain: 6',
    'douleurxx_irrad_@_triceps_G_': 'Pain irradiating to triceps Left',
    'perte_appet': 'Appetite loss',
    'lesions_peau_intens_@_2': 'Skin lesions intensity: 2',
    'trav1_@_Cara': 'Symptoms related to the Caribbean',
    'apnee': 'Apnea',
    'douleurxx_endroitducorps_@_oreille_G_': 'Pain at site: Ear Left',
    'douleurxx_carac_@_une_lourdeur_ou_serrement': 'Pain characteristic: Heaviness or tightness',
    'etouff': 'Suffocation',
    'douleurxx_irrad_@_cartilage_thyroidien': 'Pain irradiating to thyroid cartilage',
    'douleurxx_endroitducorps_@_ischio_G_': 'Pain at site: Ischium Left',
    'lesions_peau_endroitducorps_@_face_dorsale_main_D_': 'Skin lesions at site: Dorsal surface of hand Right',
    'claud_mâchoire': 'Jaw claudication',
    'cont_coq': 'Symptoms related to contact with a rooster',
    'douleurxx_endroitducorps_@_épaule_G_': 'Pain at site: Shoulder Left',
    'f32': 'Major depressive disorder, single episode',
    
    'i73.9': 'Peripheral vascular disease, unspecified',
    'lesions_peau_prurit_@_1': 'Skin lesions with itching: 1',
    'atcdfam_mg': 'No specific symptom provided',
    'scombroide': 'Symptoms of scombroid poisoning',
    'criseasthm': 'Symptoms of asthma attack',
    'douleurxx_endroitducorps_@_trachée': 'Pain at site: Trachea',
    'bode': 'No specific symptom provided',
    'oedeme_endroitducorps_@_joue_G_': 'Edema at site: Cheek Left',
    'douleurxx_endroitducorps_@_cheville_G_': 'Pain at site: Ankle Left',
    'surg1': 'Surgical procedure performed',
    'lesions_peau_endroitducorps_@_gencive_supérieure': 'Skin lesions at site: Upper gum',
    'lesions_peau_elevee_@_1': 'Elevated skin lesions: 1',
    'ap_asian': 'No specific symptom provided',
    'douleurxx_endroitducorps_@_petit_orteil__4__G_': 'Pain at site: Little toe (4th) Left',
    'douleurxx_endroitducorps_@_coude_D_': 'Pain at site: Elbow Right',
    'lesions_peau_elevee_@_2': 'Elevated skin lesions: 2',
    'douleurxx_endroitducorps_@_occiput': 'Pain at site: Occiput',
    'douleurxx_carac_@_écoeurante': 'Pain characteristic: Nauseating',
    'douleurxx_endroitducorps_@_côté_du_thorax_D_': 'Pain at site: Thoracic side Right',
    'rhino_clair': 'Clear rhinitis symptoms',
    'douleurxx_soudain_@_8': 'Sudden pain: 8',
    'paresthesies_bilat': 'Bilateral paresthesias',
    'ww_dd': 'Symptoms of World War II related diseases',
    'ulcères_bouche': 'Mouth ulcers',
    'lesions_peau_endroitducorps_@_fosse_iliaque_D_': 'Skin lesions at site: Right iliac fossa',
    'douleurxx_soudain_@_9': 'Sudden pain: 9',
    'oedeme_endroitducorps_@_coté_lateral_du_pied_D_': 'Edema at site: Lateral side of foot Right',
    'douleurxx_endroitducorps_@_doigt_majeur__G_': 'Pain at site: Middle finger Left',
    'lesions_peau_endroitducorps_@_lèvre_inferieure_D_': 'Skin lesions at site: Lower lip Right',
    'douleurxx_endroitducorps_@_nulle_part': 'Pain at no specific site',
    'lesions_peau_endroitducorps_@_face_dorsale_main_G_': 'Skin lesions at site: Dorsal side of hand Left',
    'palpit': 'Palpitations',
    'douleurxx_endroitducorps_@_doigt_index__D_': 'Pain at site: Index finger Right',
    'lesions_peau_prurit_@_4': 'Skin lesions with itching: 4',
    'diplopie': 'Double vision',
    'lesions_peau_endroitducorps_@_commissure_D_': 'Skin lesions at site: Corner of mouth Right',
    'douleurxx_carac_@_lancinante_/_choc_électrique': 'Pain characteristic: Shooting/electric shock-like',
    'drogues_IV': 'Symptoms related to intravenous drug use',
    'douleurxx_endroitducorps_@_genou_D_': 'Pain at site: Knee Right',
    'ap_pneumothorax': 'No specific symptom provided',
    'j33': 'Nasal polyps',
    'lesions_peau_endroitducorps_@_thorax_postérieur_D_': 'Skin lesions at site: Posterior thorax Right',
    'e78.5': 'Hyperlipidemia, unspecified',
    'lesions_peau_elevee_@_3': 'Elevated skin lesions: 3',
    'fievre': 'Fever',
    'lesions_peau_endroitducorps_@_lèvre_supérieure_D_': 'Skin lesions at site: Upper lip Right',
    'lesions_peau_endroitducorps_@_côté_du_cou_D_': 'Skin lesions at site: Side of neck Right',
    'lesions_peau_endroitducorps_@_fosse_iliaque_G_': 'Skin lesions at site: Left iliac fossa',
    'i50': 'Heart failure',
    'ap_hypert4': 'No specific symptom provided',
    
    'trav1_@_AsieSSE': 'Symptoms related to travel in Southeast Asia',
    'douleurxx_precis_@_7': 'Precise pain: 7',
    'trismus': 'Trismus',
    'douleurxx_endroitducorps_@_ventre': 'Pain at site: Abdomen',
    'trav1_@_Euro': 'Symptoms related to travel in Europe',
    'j45': 'Asthma',
    'z92.25': 'Personal history of long-term (current) use of anticoagulants',
    'douleurxx_endroitducorps_@_doigt_majeur__D_': 'Pain at site: Middle finger Right',
    'oedeme_endroitducorps_@_orteil__1__G_': 'Edema at site: Toe (1st) Left',
    'lesions_peau_intens_@_3': 'Skin lesions intensity: 3',
    'douleurxx_endroitducorps_@_amygdale_G_': 'Pain at site: Tonsil Left',
    'rds_paresthesie_gen': 'Generalized paresthesia',
    'c00-d48': 'Neoplasms',
    'fatigabilité_msk': 'Muscle fatigue',
    'douleurxx_endroitducorps_@_joue_G_': 'Pain at site: Cheek Left',
    'douleurxx_irrad_@_biceps_D_': 'Pain irradiating to biceps Right',
    'drogues_stimul': 'Symptoms related to stimulant drug use',
    'douleurxx_endroitducorps_@_face_dorsale_du_poignet_G_': 'Pain at site: Dorsal side of wrist Left',
    'pls_irreg': 'Irregular pulse',
    'lesions_peau_elevee_@_7': 'Elevated skin lesions: 7',
    'rural': 'Symptoms associated with rural living',
    'rds_anorexie': 'Anorexia',
    'preg1': 'Symptoms related to pregnancy',
    'ww_effort': 'Symptoms related to World War I',
    'douleurxx_endroitducorps_@_oeil_D_': 'Pain at site: Eye Right',
    'etourdissement': 'Dizziness',
    'douleurxx_soudain_@_5': 'Sudden pain: 5',
    'lymphoedème': 'Edema due to lymphatic obstruction',
    'douleurxx_irrad_@_bas_du_thorax': 'Pain irradiating to lower thorax',
    'momasthma': 'Symptoms of asthma in the mother',
    'fam_atopie': 'Family history of atopy',
    'douleurxx_intens_@_7': 'Pain intensity: 7',
    'dyspn': 'Dyspnea',
    'trav1_@_AmerC': 'Symptoms related to travel in Central America',
    'prurit_nasal': 'Nasal pruritus',
    'atcd_cluster': 'Cluster headache history',
    'douleurxx_irrad_@_triceps_D_': 'Pain irradiating to triceps Right',
    'sahs': 'Symptoms related to sleep apnea-hypopnea syndrome',
    'tmine': 'No specific symptom provided',
    'menarche_hat': 'Symptoms related to menarche',
    'douleurxx_irrad_@_nulle_part': 'Pain irradiating to no specific site',
    'lesions_peau_couleur_@_jaune': 'Yellow skin lesions',
    'lesions_peau_endroitducorps_@_nez': 'Skin lesions at site: Nose',
    'douleurxx_intens_@_5': 'Pain intensity: 5',
    'douleurxx_carac_@_un_tiraillement': 'Pain characteristic: Pulling',
    'flushing': 'Flushing',
    'douleurxx_intens_@_0': 'Pain intensity: 0',
    'oedeme_endroitducorps_@_mollet_G_': 'Edema at site: Calf Left',
    'douleurxx_endroitducorps_@_tibia_D_': 'Pain at site: Shin Right',
    'douleurxx_irrad_@_sous_la_machoire': 'Pain irradiating to submandibular region',


    
    
    'douleurxx_endroitducorps_@_hanche_D_': 'Pain at site: Hip Right',
    'douleurxx_endroitducorps_@_plante_du_pied_G_': 'Pain at site: Sole of foot Left',
    'lesions_peau_prurit_@_3': 'Pruritus at site: 3',
    'douleurxx_intens_@_3': 'Pain intensity: 3',
    'histfammigraine': 'Family history of migraine',
    'douleurxx_intens_@_2': 'Pain intensity: 2',
    'z77.22': 'Contact with and (suspected) exposure to hazardous chemical agents',
    'hernie_hiatale': 'Symptoms related to hiatal hernia',
    'convulsion': 'Convulsion',
    'douleurxx_irrad_@_tempe_D_': 'Pain irradiating to temple Right',
    'rhino_pur': 'Purulent rhinitis',
    'oedeme_endroitducorps_@_face_dorsale_du_pied_D_': 'Edema at site: Dorsal side of foot Right',
    'horm1': 'No specific symptom provided',
    'z80.0': 'Family history of glaucoma',
    'contact': 'Contact with health services',
    'f17.210': 'Nicotine dependence, cigarettes, uncomplicated',
    'douleurxx_carac_@_NA': 'Pain characteristic: Not applicable',
    'douleurxx_endroitducorps_@_ischio_D_': 'Pain at site: Ischium Right',
    'douleurxx_endroitducorps_@_palais': 'Pain at site: Palate',
    'sex_vih': 'Symptoms associated with HIV infection',
    'douleurxx_endroitducorps_@_doigt_auriculaire__D_': 'Pain at site: Little finger Right',
    'lesions_peau_endroitducorps_@_colonne_lombaire': 'Skin lesions at site: Lumbar spine',
    'douleurxx_intens_@_10': 'Pain intensity: 10',
    'douleurxx_irrad_@_côté_du_thorax_D_': 'Pain irradiating to side of thorax Right',
    'fatig_ext': 'Extreme fatigue',
    'lesions_peau_intens_@_8': 'Skin lesions intensity: 8',
    'j17_j18': 'Pneumonia',
    'cafe': 'Symptoms related to caffeine consumption',
    'douleurxx_endroitducorps_@_oreille_D_': 'Pain at site: Ear Right',
    'douleurxx_endroitducorps_@_pharynx': 'Pain at site: Pharynx',
    'lesions_peau_endroitducorps_@_dessus_de_la_langue': 'Skin lesions at site: Surface of tongue',
    'douleurxx_endroitducorps_@_omoplate_D_': 'Pain at site: Scapula Right',
    'lesions_peau_intens_@_4': 'Skin lesions intensity: 4',
    'douleurxx_carac_@_une_pulsation': 'Pain characteristic: Pulsating',
    'trav1_@_AfriqO': 'Symptoms related to travel in West Africa',
    'lesions_peau_prurit_@_7': 'Pruritus at site: 7',
    'I30': 'Acute pericarditis',
    'lesions_peau_elevee_@_0': 'Elevated skin lesions: 0',
    'douleurxx_endroitducorps_@_testicule_G_': 'Pain at site: Testicle Left',
    'lesions_peau_endroitducorps_@_colonne_cervicale': 'Skin lesions at site: Cervical spine',
    'douleurxx_endroitducorps_@_triceps_D_': 'Pain at site: Triceps Right',
    'lesions_peau_endroitducorps_@_bouche': 'Skin lesions at site: Mouth',
    'crach_sg': 'Sputum production: Sanguineous',
    'z84.89': 'Family history of other specified conditions',
    'douleurxx_carac_@_pénible': 'Pain characteristic: Distressing',
    'douleurxx_irrad_@_tempe_G_': 'Pain irradiating to temple Left',
    'douleurxx_endroitducorps_@_fosse_iliaque_G_': 'Pain at site: Iliac fossa Left',
    'atcd_anem': 'Family history of anemia',
    'douleurxx_irrad_@_épaule_D_': 'Pain irradiating to shoulder Right',
    'lesions_peau_couleur_@_NA': 'Skin lesions color: Not applicable',

    'ww_nuit': 'No specific symptom provided',
    'itss_risque': 'Symptoms related to sexually transmitted infections',
    'nau_psy_recent': 'Recent nausea related to psychiatric conditions or treatments',
    'toux_Aboy': 'Cough in children',
    'douleurxx_carac_@_violente': 'Pain characteristic: Violent',
    'douleurxx_precis_@_6': 'Precise pain: 6',
    'douleurxx_endroitducorps_@_haut_du_thorax': 'Pain at site: Upper thorax',
    'vo_violent': 'Violent behavior',
    'diarrhee': 'Diarrhea',
    'lesions_peau_endroitducorps_@_palais': 'Skin lesions at site: Palate',
    'melena': 'Melena',
    'lesions_peau_prurit_@_8': 'Pruritus at site: 8',
    'douleurxx_endroitducorps_@_hypochondre_G_': 'Pain at site: Hypochondrium Left',
    'douleurxx_endroitducorps_@_orteil__3__G_': 'Pain at site: Toe (3rd) Left',
    'douleurxx_endroitducorps_@_face_dorsale_du_poignet_D_': 'Pain at site: Dorsal side of wrist Right',
    'crohn_cu': "Symptoms of Crohn's disease involving the colon",
    'osteoporose': 'Symptoms of osteoporosis',
    'perte_poids': 'Weight loss',
    'douleurxx_soudain_@_4': 'Sudden pain: 4',
    'trav1_@_AfriqSS': 'Symptoms related to travel in sub-Saharan Africa',
    'douleurxx_irrad_@_côté_du_thorax_G_': 'Pain irradiating to side of thorax Left',
    'lesions_peau_endroitducorps_@_colonne_dorsale': 'Skin lesions at site: Dorsal spine',
    'toux': 'Cough',
    'naco': 'No specific symptom provided',
    'oedeme_endroitducorps_@_tibia_D_': 'Edema at site: Tibia Right',
    'H6690': 'Sensorineural hearing loss, unspecified, unspecified ear',
    'douleurxx_precis_@_3': 'Precise pain: 3',
    'douleurxx_endroitducorps_@_amygdale_D_': 'Pain at site: Tonsil Right',
    'psy_depers': 'Depersonalization',
    'lesions_peau_endroitducorps_@_grande_lèvre_G_': 'Skin lesions at site: Labium majus Left',
    'lesions_peau_endroitducorps_@_sous_la_langue': 'Skin lesions at site: Under the tongue',
    'fam_j45': 'Family history of asthma',
    'synd_nephro': 'Nephrological syndrome',
    'ebolacase': 'Suspected case of Ebola virus disease',
    'lesions_peau_prurit_@_0': 'Pruritus at site: 0',
    'lesions_peau_endroitducorps_@_scrotum': 'Skin lesions at site: Scrotum',
    'lesions_peau_endroitducorps_@_cuisse_G_': 'Skin lesions at site: Thigh Left',
    'douleurxx_soudain_@_1': 'Sudden pain: 1',
    'douleurxx_irrad_@_nez': 'Pain irradiating to nose',
    'douleurxx_endroitducorps_@_front': 'Pain at site: Forehead',
    'lesions_peau_endroitducorps_@_joue_interne_G_': 'Skin lesions at site: Inner cheek Left',
    'lesions_peau_endroitducorps_@_biceps_G_': 'Skin lesions at site: Biceps Left',
    'oedeme_endroitducorps_@_plante_du_pied_G_': 'Edema at site: Sole of foot Left',
    'wheez': 'Wheezing',
    'J05.0': 'Acute obstructive laryngitis [croup]',
    'douleurxx_endroitducorps_@_genou_G_': 'Pain at site: Knee Left',
    'douleurxx_endroitducorps_@_coude_G_': 'Pain at site: Elbow Left',
    'wakeup': 'Difficulty waking up',
    'f41.9': 'Anxiety disorder, unspecified',
    'douleurxx_irrad_@_menton': 'Pain irradiating to chin',
    
    'obstipation': 'Obstipation',
    'lesions_peau_endroitducorps_@_thorax_postérieur_G_': 'Skin lesions at site: Posterior thorax Left',
    'erytheme_occ': 'Erythema occurring',
    'lesions_peau_intens_@_5': 'Skin lesions intensity: 5',
    'douleurxx_soudain_@_10': 'Sudden pain: 10',
    'douleurxx_irrad_@_sein_G_': 'Pain irradiating to breast Left',
    'oedeme_endroitducorps_@_arrière_de_la_cheville_G_': 'Edema at site: Back of ankle Left',
    'posttus_emesis': 'Post-tussive emesis',
    'adp_dlr': 'Adipose tissue disorder',
    'douleurxx_endroitducorps_@_omoplate_G_': 'Pain at site: Scapula Left',
    'k74': 'Fibrosis and cirrhosis of liver',
    'insp_siffla': 'Inspiration wheezing',
    'douleurxx_endroitducorps_@_orteil__3__D_': 'Pain at site: Toe (3rd) Right',
    'douleurxx_endroitducorps_@_arrière_de_la_cheville_G_': 'Pain at site: Back of ankle Left',
    'douleurxx_endroitducorps_@_tempe_D_': 'Pain at site: Temple Right',
    'ww_valsalva': 'Valsalva maneuver',
    'douleurxx_endroitducorps_@_mollet_D_': 'Pain at site: Calf Right',
    's09.90': 'Unspecified injury of head',
    'msk_dlr': 'Musculoskeletal disorder',
    'angor_accelere': 'Accelerated angina',
    'oedeme_endroitducorps_@_nulle_part': 'Edema at unspecified site',
    'oedeme_endroitducorps_@_orteil__1__D_': 'Edema at site: Toe (1st) Right',
    'lesions_peau_prurit_@_6': 'Skin lesions with itching: 6',
    'lesions_peau_intens_@_7': 'Skin lesions intensity: 7',
    'douleurxx_endroitducorps_@_mollet_G_': 'Pain at site: Calf Left',
    'lesions_peau_endroitducorps_@_flanc_D_': 'Skin lesions at site: Flank Right',
    'selles_pale': 'Pale stools',
    'anxiete_s': 'Anxiety',
    'lesions_peau': 'Skin lesions',
    'pneumothorax': 'Pneumothorax',
    'ww_bouffe': 'Swelling sensation',
    'douleurxx_irrad_@_colonne_dorsale': 'Pain irradiating to dorsal spine',
    'douleurxx_endroitducorps_@_colonne_dorsale': 'Pain at site: Dorsal spine',
    'douleurxx_endroitducorps_@_pouce_G_': 'Pain at site: Thumb Left',
    'lesions_peau_endroitducorps_@_épigastre': 'Skin lesions at site: Epigastrium',
    'douleurxx_soudain_@_7': 'Sudden pain: 7',
    'suburb': 'Symptoms associated with suburban living',
    'oedeme_endroitducorps_@_arrière_de_la_cheville_D_': 'Edema at site: Back of ankle Right',
    'ww_bouger': 'Pain or discomfort with movement',
    'K86.1': 'K86.1',
    'douleurxx_endroitducorps_@_hypochondre_D_': 'Pain at site: Hypochondrium Right',
    'atcdpsyfam': 'Family history of psychiatric disorders',
    'douleurxx_endroitducorps_@_côté_du_thorax_G_': 'Pain at site: Side of thorax Left',
    'urban1': 'Symptoms associated with urban living',
    'douleurxx_endroitducorps_@_coté_lateral_du_pied_G_': 'Pain at site: Lateral side of foot Left',
    'douleurxx_endroitducorps_@_triceps_G_': 'Pain at site: Triceps Left',
    'douleurxx_endroitducorps_@_biceps_G_': 'Pain at site: Biceps Left',
    'dysarthrie': 'Dysarthria',
    'Z99.2': 'Dependence on renal dialysis',
    'cortico': 'Symptoms related to corticosteroid use',
    
    'trav1_@_AmerN': 'Travel to North America',
    'volume_parole': 'Speech volume',
    'lesions_peau_prurit_@_10': 'Skin lesions with itching: 10',
    'douleurxx_endroitducorps_@_arrière_du_cou': 'Pain at site: Back of neck',
    'lesions_peau_desquame_@_N': 'Skin lesions with desquamation',
    'douleurxx_endroitducorps_@_orteil__1__G_': 'Pain at site: Toe (1st) Left',
    'douleurxx_precis_@_9': 'Precise pain: 9',
    'douleurxx_endroitducorps_@_cartilage_thyroidien': 'Pain at site: Thyroid cartilage',
    'toux_sev': 'Severe cough',
    'trav1_@_Asie': 'Travel to Asia',
    'footnumb': 'Numbness in foot',
    'f10.129': 'Alcohol abuse with dependence',
    'irc': 'Chronic kidney disease',
    'douleurxx_precis_@_4': 'Precise pain: 4',
    'douleurxx_endroitducorps_@_testicule_D_': 'Pain at site: Testicle Right',
    'douleurxx_endroitducorps_@_arrière_de_la_cheville_D_': 'Pain at site: Back of ankle Right',
    'douleurxx_precis_@_0': 'Precise pain: 0',
    'douleurxx_endroitducorps_@_aisselle_D_': 'Pain at site: Armpit Right',
    'lesions_peau_endroitducorps_@_fesse_D_': 'Skin lesions at site: Buttock Right',
    'oedeme_endroitducorps_@_orteil__2__D_': 'Edema at site: Toe (2nd) Right',
    'lesions_peau_couleur_@_rouge': 'Reddish skin lesions',
    'lesions_peau_endroitducorps_@_cuisse_D_': 'Skin lesions at site: Thigh Right',
    'douleurxx_precis_@_8': 'Precise pain: 8',
    'douleurxx_endroitducorps_@_talon_D_': 'Pain at site: Heel Right',
    'oedeme_endroitducorps_@_tibia_G_': 'Edema at site: Tibia Left',
    'dysp_effort': 'Dyspnea on exertion',
    'regard_dévié': 'Deviation of gaze',
    'douleurxx_endroitducorps_@_face_palmaire_du_poignet_G_': 'Pain at site: Palmar side of wrist Left',
    'HIV': 'Human Immunodeficiency Virus (HIV)',
    'lesions_peau_endroitducorps_@_côté_du_cou_G_': 'Skin lesions at site: Side of neck Left',
    'ballon_abdo': 'Abdominal distension',
    'pale': 'Pallor',
    'douleurxx_irrad_@_biceps_G_': 'Pain irradiating to biceps Left',
    'angor_repos': 'Angina at rest',
    'douleurxx_endroitducorps_@_coté_lateral_du_pied_D_': 'Pain at site: Lateral side of foot Right',
    'expecto': 'Expectoration',
    'atcd_fam_anem': 'Family history of anemia',
    'oedeme_endroitducorps_@_mollet_D_': 'Edema at site: Calf Right',
    'fatig_mod': 'Moderate fatigue',
    'hosptisasm': 'Asthma requiring hospitalization',
    'lesions_peau_plusqu1cm_@_N': 'Skin lesions larger than 1cm',
    'eampoc1': 'Earache',
    'allergie_sev': 'Severe allergy',
    'lesions_peau_endroitducorps_@_cheville_G_': 'Skin lesions at site: Ankle Left',
    'douleurxx_endroitducorps_@_tempe_G_': 'Pain at site: Temple Left',
    'douleurxx_endroitducorps_@_fosse_iliaque_D_': 'Pain at site: Iliac fossa Right',
    'paralysie_visage': 'Facial paralysis',
    'hta': 'Hypertension',
    'lesions_peau_prurit_@_5': 'Skin lesions with itching: 5',

    'douleurxx_endroitducorps_@_joue_D_': 'Pain at site: Cheek Right',
    'douleurxx_endroitducorps_@_tibia_G_': 'Pain at site: Shin Left',
    'ww_respi': 'Respiratory distress',
    'lesions_peau_elevee_@_4': 'Elevated skin lesions: 4',
    'stridor': 'Stridor',
    'douleurxx_endroitducorps_@_sein_D_': 'Pain at site: Breast Right',
    'lesions_peau_endroitducorps_@_flanc_G_': 'Skin lesions at site: Flank Left',
    'lesions_peau_endroitducorps_@_arrière_du_cou': 'Skin lesions at site: Back of neck',
    'i60-i69': 'Cerebrovascular diseases',
    'lesions_peau_endroitducorps_@_testicule_G_': 'Skin lesions at site: Testicle Left',
    'rds_sg': 'Respiratory distress at rest',
    'lesions_peau_intens_@_1': 'Skin lesions intensity: 1',
    'oedeme_endroitducorps_@_coté_lateral_du_pied_G_': 'Edema at site: Lateral side of foot Left',
    'hyponos': 'Hypnogogic hallucinations',
    'douleurxx_endroitducorps_@_côté_du_cou_G_': 'Pain at site: Side of neck Left',
    'douleurxx_soudain_@_2': 'Sudden pain: 2',
    'lesions_peau_endroitducorps_@_gencive_inférieure': 'Skin lesions at site: Lower gum',
    'impression_mort': 'Impression of death',
    'lesions_peau_elevee_@_5': 'Elevated skin lesions: 5',
    'lesions_peau_endroitducorps_@_grande_lèvre_D_': 'Skin lesions at site: Labia majora Right',
    'nausee': 'Nausea',
    'rds_paralys_gen': 'Respiratory distress with generalized paralysis',
    'douleurxx_carac_@_une_brûlure_ou_chaleur': 'Burning or heat sensation',
    'v85.0': 'Body mass index 40.0 and over, adult',
    'oedeme_endroitducorps_@_cheville_D_': 'Edema at site: Ankle Right',
    'faiblesse_msmi': 'Muscle weakness',
    'douleurxx_irrad_@_omoplate_G_': 'Pain irradiating to scapula Left',
    'oedeme_endroitducorps_@_cuisse_G_': 'Edema at site: Thigh Left',
    'rectorragie': 'Rectal bleeding',
    'lesions_peau_prurit_@_2': 'Skin lesions itching: 2',
    'allait_prol': 'Prolonged breastfeeding',
    'douleurxx_irrad_@_thorax_postérieur_D_': 'Pain irradiating to posterior thorax Right',
    'douleurxx_irrad_@_arrière_de_tête': 'Pain irradiating to back of head',
    'douleurxx_precis_@_10': 'Precise pain: 10',
    'lesions_peau_prurit_@_9': 'Skin lesions itching: 9',
    'douleurxx_endroitducorps_@_doigt_auriculaire__G_': 'Pain at site: Finger (little finger) Left',
    'ains': 'Nonsteroidal anti-inflammatory drugs (NSAIDs)',
    'z80.1': 'Family history of malignant neoplasm of genitourinary organs',
    'spasmes_msk': 'Muscle spasms',
    'friss': 'Frission (chills)',
    'lesions_peau_endroitducorps_@_testicule_D_': 'Skin lesions at site: Testicle Right',
    'lesions_peau_elevee_@_6': 'Elevated skin lesions: 6',
    'douleurxx_endroitducorps_@_thorax_postérieur_D_': 'Pain at site: Posterior thorax Right',
    'crowd': 'Crowding',
    'douleurxx_intens_@_9': 'Pain intensity: 9',
    'lesions_peau_endroitducorps_@_front': 'Skin lesions at site: Forehead',
    'douleurxx_endroitducorps_@_thorax_postérieur_G_': 'Pain at site: Posterior thorax Left',
    'douleurxx_irrad_@_front': 'Pain irradiating to forehead',
    'douleurxx_endroitducorps_@_face_palmaire_du_poignet_D_': 'Pain at site: Palmar surface of wrist Right',
    'lesions_peau_endroitducorps_@_petite_lèvre_D_': 'Skin lesions at site: Labia minora Right',
    
    
    'douleurxx_endroitducorps_@_cuisse_D_': 'Pain at site: Thigh Right',
    'trav1_@_AfriqN': 'Travel history: Africa North',
    'douleurxx_carac_@_épeurante': 'Pain characteristic: Frightening',
    'protu_langue': 'Protrusion of the tongue',
    'douleurxx_endroitducorps_@_flanc_D_': 'Pain at site: Flank Right',
    'douleurxx_carac_@_déchirante': 'Pain characteristic: Tearing',
    'lesions_peau_endroitducorps_@_nulle_part': 'Skin lesions at site: None',
    'diaph': 'Diaphoresis (excessive sweating)',
    'douleurxx_endroitducorps_@_doigt_annulaire__G_': 'Pain at site: Finger (ring finger) Left',
    'douleurxx_carac_@_une_crampe': 'Pain characteristic: Cramping',
    'lesions_peau_endroitducorps_@_joue_interne_D_': 'Skin lesions at site: Inner cheek Right',
    'douleurxx_soudain_@_3': 'Sudden pain: 3',
    'douleurxx_intens_@_4': 'Pain intensity: 4',
    'e66': 'Overweight and obesity',
  
    'douleurxx': 'Pain',
    'douleurxx_carac_@_un_coup_de_couteau': 'Pain characteristic: Stabbing',
    'douleurxx_endroitducorps_@_amygdale_D_': 'Pain at site: Tonsil Right',
    'douleurxx_endroitducorps_@_amygdale_G_': 'Pain at site: Tonsil Left',
    'douleurxx_endroitducorps_@_pharynx': 'Pain at site: Pharynx',
    'douleurxx_endroitducorps_@_sous_la_machoire': 'Pain at site: Under the jaw',
    'douleurxx_endroitducorps_@_trachée': 'Pain at site: Trachea',
    'douleurxx_intens_@_5': 'Pain intensity: 5',
    'douleurxx_irrad_@_nulle_part': 'Pain radiation: None',
    'douleurxx_precis_@_10': 'Precise pain: 10',
    'douleurxx_soudain_@_4': 'Sudden pain: 4',
    'dyspn': 'Dyspnea (shortness of breath)',
    'f10.129': 'Alcohol abuse with intoxication',
    'fievre': 'Fever',
    'sialorhee': 'Excessive salivation',
    'stridor': 'Stridor (high-pitched breathing sound)',
    'trav1_@_N': 'Travel history: Unknown',
    'vaccination': 'Vaccination',
    'volume_parole': 'Speech volume',
    
    'IVRS ou virémie': 'IVRS or viremia',
    'VIH (Primo-infection)': 'HIV (initial infection)',
    'Pneumonie': 'Pneumonia',
    'Rhinosinusite chronique': 'Chronic rhinosinusitis',
    'Pharyngite virale': 'Viral pharyngitis',
    'Anémie': 'Anemia',
    'Fibrillation auriculaire/Flutter auriculaire': 'Atrial fibrillation/Atrial flutter',
    'Rhinite allergique': 'Allergic rhinitis',
    'Laryngospasme': 'Laryngospasm',
    'Céphalée en grappe': 'Cluster headache',
    'Anaphylaxie': 'Anaphylaxis',
    'Pneumothorax spontané': 'Spontaneous pneumothorax',
    'OAP/Surcharge pulmonaire': 'Pulmonary edema/Pulmonary overload',
    'Tuberculose': 'Tuberculosis',
    'Myasthénie grave': 'Myasthenia gravis',
    'Attaque de panique': 'Panic attack',
    'Scombroïde': 'Scombroid',
    'Épiglottite': 'Epiglottitis',
    'Hernie inguinale': 'Inguinal hernia',
    'Syndrome de Boerhaave': 'Boerhaave syndrome',
    'Néoplasie du pancréas': 'Pancreatic neoplasm',
    'Bronchite': 'Bronchitis',
    'Lupus érythémateux disséminé (LED)': 'Systemic lupus erythematosus (SLE)',
    'Laryngite aigue': 'Acute laryngitis',
    'Angine instable': 'Unstable angina',
    'Bronchiectasies': 'Bronchiectasis',
    'Possible NSTEMI / STEMI': 'Possible NSTEMI/STEMI',
    'Chagas': 'Chagas disease',
    'Oedème localisé ou généralisé sans atteinte pulmonaire associée': 'Localized or generalized edema without associated pulmonary involvement',
    'Sarcoïdose': 'Sarcoidosis',
    'Fracture de côte spontanée': 'Spontaneous rib fracture',
    'RGO': 'GERD',
    'Asthme exacerbé ou bronchospasme': 'Exacerbated asthma or bronchospasm',
    'Exacerbation aigue de MPOC et/ou surinfection associée': 'Acute exacerbation of COPD and/or associated superinfection',
    'Syndrome de Guillain-Barré': 'Guillain-Barré syndrome',
    'Possible influenza ou syndrome virémique typique': 'Possible influenza or typical viremic syndrome',
    'Embolie pulmonaire': 'Pulmonary embolism',
    'Angine stable': 'Stable angina',
    'Péricardite': 'Pericarditis',
    'Rhinosinusite aigue': 'Acute rhinosinusitis',
    'Coqueluche': 'Whooping cough',
    'Myocardite': 'Myocarditis',
    'Réaction dystonique aïgue': 'Acute dystonic reaction',
    'néoplasie pulmonaire': 'Lung neoplasm',
    'Otite moyenne aigue (OMA)': 'Acute otitis media (AOM)',
    'TSVP': 'BPVT',
    'Laryngo-trachéo-bronchite (Croup)': 'Laryngo-tracheo-bronchitis (Croup)',
    'Ebola': 'Ebola',
    'Bronchiolite': 'Bronchiolitis',
    'perinatality': 'Symptoms related to the perinatal period',
    'fam_atopie': 'Family history of atopy',
    'bode': 'No specific symptom provided',
    'menarche_hat': 'Symptoms related to menarche',
    'allait_prol': 'Prolonged breastfeeding',
    'hosptisasm': 'Symptoms associated with hospitalization',
    'Mauv_aliment': 'Symptoms related to food poisoning',
    'eampoc1': 'No specific symptom provided',
    'atcdfam_mg': 'No specific symptom provided',
    'itss_risque': 'Symptoms related to sexually transmitted infections',
    'norvasc': 'Side effects or symptoms associated with Norvasc',
    'atcdpsyfam': 'Family history of psychiatric disorders',
    'hernie_hiatale': 'Symptoms related to hiatal hernia',
    'tconst': 'No specific symptom provided',
    'immob1': 'Symptoms related to immobility',
    'sex_vih': 'Symptoms associated with HIV infection',
    'momasthma': 'Symptoms of asthma in the mother',
    'criseasthm': 'Symptoms of asthma attack',
    'wakeup': 'Difficulty waking up',
    'move': 'Difficulty with movement',
    'crowd': 'Discomfort or symptoms worsened in crowded places',
    'cafe': 'Symptoms related to caffeine consumption',
    'lymphoedÃƒÂ¨me': 'Swelling due to lymphatic obstruction',
    'naco': 'No specific symptom provided',
    'ains': 'Symptoms related to NSAID use',
    'dayc': 'Symptoms occurring during the day',
    'ap_par': 'No specific symptom provided',
    'pneumothorax': 'Symptoms of pneumothorax',
    'tmine': 'No specific symptom provided',
    'ap_pneumothorax': 'No specific symptom provided',
    'antipsy_rÃƒÂ©cent': 'Recent antipsychotic medication use or withdrawal symptoms',
    'drogues_IV': 'Symptoms related to intravenous drug use',
    'crohn_cu': "Symptoms of Crohn's disease involving the colon",
    'scombroide': 'Symptoms of scombroid poisoning',
    'trav1': 'Symptoms related to travel',
    'cont_coq': 'No specific symptom provided',
    'drogues_stimul': 'Symptoms related to stimulant drug use',
    'ap_asian': 'No specific symptom provided',
    'patho_endo': 'Symptoms related to endocrine disorders',
    'hta': 'Symptoms of hypertension',
    'atcd_its': 'Symptoms related to history of sexually transmitted infections',
    'nau_psy_recent': 'Recent nausea related to psychiatric conditions or treatments',
    'suburb': 'Symptoms associated with suburban living',
    'rx_vasodil': 'Symptoms related to vasodilator medication use',
    'fam_j45': 'Family history of asthma',
    'osteoporose': 'Symptoms of osteoporosis',
    'rural': 'Symptoms associated with rural living',
    'preg1': 'Symptoms',
    'HIV':'HIV'

}


 # Default input_value if not provided as argument
def find_output(input_value):
    with open(r'E:\MediNexus\Medicine5.csv','r',encoding='utf-8') as csvfile:
        reader=csv.DictReader(csvfile)
        for row in reader:
            count=len(input_value)
            for i in input_value:
                print(i)
                if(i in row['EVIDENCES']):
                    print(i)
                    count-=1

            if(count<=1):
                output_data = row['DIFFERENTIAL_DIAGNOSIS']
                dit = {}
                for i in ast.literal_eval(output_data):
                    flagfordict=0
                    for j in i:
                        if(isinstance(j,str)):
                            key=mediu[j]  # Assuming 'mediu' is defined somewhere
                            flagfordict+=1
                        else:
                            value=j
                            flagfordict+=1
                        if(flagfordict==2):
                            dit[key]=value
                return json.dumps(dit)

    return None

if __name__ == "__main__":
    if len(sys.argv) > 1:
        input_value = json.loads(sys.argv[1])
    result = find_output(input_value)
    print(result)
